# Generated by Django 2.1.1 on 2018-09-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_Of_Tesch_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=500)),
                ('affliation', models.CharField(max_length=200)),
                ('year_of_establishment', models.IntegerField()),
                ('postal_code', models.CharField(max_length=6)),
                ('school_landline', models.CharField(max_length=15)),
                ('school_mobile', models.CharField(max_length=15)),
                ('school_type', models.CharField(max_length=50)),
            ],
        ),
    ]
