# Generated by Django 2.1.1 on 2018-09-03 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tesch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_tesch_users',
            name='school_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
