# Generated by Django 2.1.1 on 2018-09-03 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tesch', '0002_list_of_tesch_users_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_tesch_users',
            name='account_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
